/* tools/fontgen/gen_inter.c — HOST-SIDE generator (DDR-728): rasterize the
 * Inter typeface (SIL OFL 1.1) into an embedded bitmap glyph atlas for the
 * compositor. Runs on the build host only — never part of the OS image.
 *
 *   cc -O2 -o gen_inter gen_inter.c -lm
 *   ./gen_inter Inter-Regular.ttf 16 > user/inter_font.h
 *
 * Output: 8-bit alpha glyphs for ASCII 0x20..0x7E at the requested pixel
 * height, with per-glyph metrics (width, advance, x/y offset). The rendered
 * bitmaps are not font software; Inter's OFL does not restrict rendered
 * output. Attribution retained in the generated header.
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define STB_TRUETYPE_IMPLEMENTATION
#include "stb_truetype.h"

int main(int argc, char **argv) {
    if (argc < 3) { fprintf(stderr, "usage: %s font.ttf px\n", argv[0]); return 1; }
    FILE *f = fopen(argv[1], "rb");
    if (!f) { perror("font"); return 1; }
    fseek(f, 0, SEEK_END); long len = ftell(f); fseek(f, 0, SEEK_SET);
    unsigned char *ttf = malloc((size_t)len);
    if (fread(ttf, 1, (size_t)len, f) != (size_t)len) { perror("read"); return 1; }
    fclose(f);

    stbtt_fontinfo fi;
    if (!stbtt_InitFont(&fi, ttf, stbtt_GetFontOffsetForIndex(ttf, 0))) {
        fprintf(stderr, "bad font\n"); return 1;
    }
    int px = atoi(argv[2]);
    float scale = stbtt_ScaleForPixelHeight(&fi, (float)px);
    int ascent, descent, linegap;
    stbtt_GetFontVMetrics(&fi, &ascent, &descent, &linegap);

    printf("/* user/inter_font.h — GENERATED by tools/fontgen/gen_inter.c (DDR-728).\n"
           " * Rasterized from Inter (c) The Inter Project Authors, SIL OFL 1.1\n"
           " * (https://github.com/rsms/inter). Rendered bitmaps; not font software.\n"
           " * ASCII 0x20..0x7E at %dpx. Do not edit by hand — regenerate. */\n"
           "#pragma once\n\n", px);
    printf("#define INTER_PX      %d\n", px);
    printf("#define INTER_ASCENT  %d\n", (int)((float)ascent * scale + 0.5f));
    printf("#define INTER_FIRST   0x20\n#define INTER_LAST    0x7E\n\n");
    printf("struct inter_glyph { unsigned short off; unsigned char w, h; "
           "signed char xoff, yoff; unsigned char adv; };\n\n");

    unsigned char *pix = NULL; size_t cap = 0, total = 0;
    struct { int off, w, h, xo, yo, adv; } g[95];

    for (int c = 0x20; c <= 0x7E; c++) {
        int w, h, xo, yo, adv, lsb;
        unsigned char *bmp = stbtt_GetCodepointBitmap(&fi, scale, scale, c, &w, &h, &xo, &yo);
        stbtt_GetCodepointHMetrics(&fi, c, &adv, &lsb);
        int i = c - 0x20;
        g[i].off = (int)total; g[i].w = w; g[i].h = h; g[i].xo = xo; g[i].yo = yo;
        g[i].adv = (int)((float)adv * scale + 0.5f);
        size_t n = (size_t)w * (size_t)h;
        if (total + n > cap) { cap = (total + n) * 2 + 256; pix = realloc(pix, cap); }
        memcpy(pix + total, bmp, n);
        total += n;
        stbtt_FreeBitmap(bmp, NULL);
    }

    printf("static const struct inter_glyph inter_glyphs[95] = {\n");
    for (int i = 0; i < 95; i++)
        printf("    {%d, %d, %d, %d, %d, %d},\n",
               g[i].off, g[i].w, g[i].h, g[i].xo, g[i].yo, g[i].adv);
    printf("};\n\nstatic const unsigned char inter_pixels[%zu] = {\n", total);
    for (size_t i = 0; i < total; i++)
        printf("%d,%s", pix[i], (i % 24 == 23) ? "\n" : "");
    printf("\n};\n");
    fprintf(stderr, "atlas: %zu bytes of pixels\n", total);
    return 0;
}
