#!/usr/bin/env python3
"""tools/ci/fetch_mldsa_kat.py — regenerate kernel/crypto/mldsa_kat.h, DDR-1053.

PROVENANCE, NOT A ONE-OFF DOWNLOAD. The pinned ML-DSA vectors must be traceable
to an authority, and re-derivable by anyone who doubts them, so the fetch is a
committed tool rather than something that happened once in a session.

SOURCE: NIST's own ACVP server repository, FIPS 204 ML-DSA keyGen vector set.
  https://github.com/usnistgov/ACVP-Server
    gen-val/json-files/ML-DSA-keyGen-FIPS204/{prompt,expectedResults}.json

WHY THIS SOURCE. docs/PRE_LAUNCH_CHECKLIST.md §5.1b.1 fact 4 is the binding
constraint: a sign-then-verify gate passes on ANY self-consistent wrong
implementation, so FIPS 204 conformance can only be shown against fixed vectors
produced elsewhere. Fact 3 measured the routes: csrc.nist.gov is blocked by this
environment's proxy, and raw.githubusercontent.com is reachable. ACVP-Server is
NIST's own repository, so it is the authority, reached by the one open route.

keyGen is used rather than sigGen because it is DETERMINISTIC: seed -> (pk, sk)
with no signing randomness, so a mismatch is unambiguous.

CORROBORATION: the fetched lengths are checked against the FIPS 204 parameters
for ML-DSA-44 (pk 1312 B, sk 2560 B). A file that parses but has the wrong shape
is not silently accepted.
"""
import json, sys, urllib.request

BASE = ("https://raw.githubusercontent.com/usnistgov/ACVP-Server/master/"
        "gen-val/json-files/ML-DSA-keyGen-FIPS204")
PARAM_SET = "ML-DSA-44"
PK_LEN, SK_LEN, SEED_LEN = 1312, 2560, 32
N_VECTORS = 2

def get(url):
    with urllib.request.urlopen(url, timeout=120) as r:
        return json.loads(r.read().decode())

def main():
    prompt = get(f"{BASE}/prompt.json")
    if prompt.get("algorithm") != "ML-DSA" or prompt.get("revision") != "FIPS204":
        sys.exit(f"unexpected vector set: {prompt.get('algorithm')} {prompt.get('revision')}")
    expected = get(f"{BASE}/expectedResults.json")

    seeds = {t["tcId"]: t["seed"]
             for g in prompt["testGroups"] if g.get("parameterSet") == PARAM_SET
             for t in g["tests"]}
    res = {t["tcId"]: t for g in expected["testGroups"] for t in g["tests"]}

    picked = []
    for tc in sorted(seeds)[:N_VECTORS]:
        seed = bytes.fromhex(seeds[tc])
        pk = bytes.fromhex(res[tc]["pk"])
        sk = bytes.fromhex(res[tc]["sk"])
        if len(seed) != SEED_LEN or len(pk) != PK_LEN or len(sk) != SK_LEN:
            sys.exit(f"tc{tc}: wrong shape seed={len(seed)} pk={len(pk)} sk={len(sk)} "
                     f"(FIPS 204 {PARAM_SET} wants {SEED_LEN}/{PK_LEN}/{SK_LEN})")
        picked.append((tc, seed, pk, sk))

    def carr(b, per=12):
        return "\n".join("    " + " ".join(f"0x{x:02X}," for x in b[i:i+per])
                         for i in range(0, len(b), per))

    out = [__doc__.replace('"""', '').strip()]
    hdr = ["/* kernel/crypto/mldsa_kat.h — PINNED FIPS 204 ML-DSA-44 keyGen vectors.",
           " *",
           " * GENERATED by tools/ci/fetch_mldsa_kat.py from NIST's ACVP-Server repository.",
           " * DO NOT EDIT BY HAND -- re-run the tool instead, so provenance stays checkable.",
           " *",
           " * These are known-answer vectors from an authority, which is the only thing that",
           " * can show FIPS 204 conformance: a sign-then-verify gate passes on any",
           " * self-consistent wrong implementation (checklist §5.1b.1 fact 4).",
           " */",
           "#pragma once", "#include <stdint.h>", ""]
    for tc, seed, pk, sk in picked:
        hdr += [f"/* ACVP tcId {tc}, {PARAM_SET} */",
                f"static const uint8_t MLDSA44_SEED_{tc}[{SEED_LEN}] = {{\n{carr(seed)}\n}};",
                f"static const uint8_t MLDSA44_PK_{tc}[{PK_LEN}] = {{\n{carr(pk)}\n}};",
                f"static const uint8_t MLDSA44_SK_{tc}[{SK_LEN}] = {{\n{carr(sk)}\n}};", ""]
    hdr.append(f"#define MLDSA44_KAT_COUNT {len(picked)}")
    open("kernel/crypto/mldsa_kat.h", "w").write("\n".join(hdr) + "\n")
    print(f"wrote kernel/crypto/mldsa_kat.h: {len(picked)} {PARAM_SET} keyGen vectors "
          f"(tcIds {', '.join(str(t) for t,_,_,_ in picked)})")

if __name__ == "__main__":
    main()
