/* GENERATED by tools/ui/png_palette.py header -- DO NOT EDIT.
 * DDR-1147 sec.1.4/1.5: accents measured from the PNGs in docs/ui/reference,
 * theme names by the operator's colour rule (PR #17 comment 5845610518).
 * `make ci-palette-check` regenerates this file and cmp's it.
 *
 * 02_28_47 top L=0.272 hue=298 warm=0.00 rule=Umbra ac=#7642D0
 * 02_28_47 bottom L=0.426 hue=263 warm=0.01 rule=Aurora ac=#3073EA
 * 02_32_37 top L=0.825 hue=262 warm=0.03 rule=Zenith ac=#4C89FC
 * 02_32_37 bottom L=0.217 hue=288 warm=0.00 rule=Umbra ac=#7356B9
 * 02_47_54 top L=0.469 hue=205 warm=0.03 rule=Aurora ac=#24A6AF
 * 02_47_54 bottom L=0.280 hue=47 warm=0.74 rule=Twilight ac=#B46526
 * 02_50_44 top L=0.327 hue=45 warm=0.80 rule=Twilight ac=#C95B1A
 * 02_50_44 bottom L=0.364 hue=202 warm=0.01 rule=Aurora ac=#20A3A1
 * resolve: Consort Aurora keeps 02_50_44 bottom (d=0.021)
 * resolve: 02_28_47 bottom -> Consort Zenith (d=0.068; overrides rule=Aurora)
 */
#ifndef PRADYOS_THEME_PALETTE_H
#define PRADYOS_THEME_PALETTE_H

/* [mode][ambiance] -> accent R,G,B; mode 0 = Consort (manual), 1 = Regalia
 * (sovereign); ambiance in AMB[] order DAWN/DAY/DUSK/NIGHT. */
static const unsigned char THEME_AC[2][4][3] = {
    { {0x20,0xA3,0xA1}, {0x30,0x73,0xEA}, {0xB4,0x65,0x26}, {0x73,0x56,0xB9} },   /* Consort */
    { {0x24,0xA6,0xAF}, {0x4C,0x89,0xFC}, {0xC9,0x5B,0x1A}, {0x76,0x42,0xD0} },   /* Regalia */
};

static const char *const THEME_AMB_NAME[4] = { "Aurora", "Zenith", "Twilight", "Umbra" };
static const char *const THEME_MODE_NAME[2] = { "Consort", "Regalia" };

#endif
